language: csharp
os: linux
dist: xenial
mono: none
dotnet: 3.1
solution: aspnet-api-heroku.sln
branches:
  except:
  - feature
  only:
  - master
  - stable
script:
  - dotnet restore
  - dotnet test
