language: csharp
os: linux
dist: xenial
mono: none
dotnet: 3.1
solution: aspnet-api-heroku.sln
branches:
  except:
  - feature
  only:
  - master
  - stable
script:
- dotnet restore
- dotnet test
deploy:
  provider: heroku
  api_key:
    secure: prvFd0fxG/+TIBVqKRekVWHz8cotBckDBUTsDeU7WE5dPZgphEOCsJDEWj4pv9MAAqwitSCUyjtR4l9oSrrGGWQqOm/zChUihbUbjX8qTes0y6nH2pnM8xIueIYpmn0AhOej3vDSlCvjeqtVZLI0nkvYMsO1mRT+l0QgrJsN2WGSceSiWlV+rzUn/KI9tQs6P6xFyZiLOWQoNgJQALqCLP5mT4J0kO1b8UVI559z1G8k7Wl+uATKJWqYOAv/sueZEQjWiPvHlwI9BkXDFKmhUbkRgbkU8bt9tpi4dPrP+gN7EXmZBFx7UkfKe/aHJH/7gS9kf4v5DjMYOBEQKsJndR4SXIQ94jXkYsvUawFIhHwJNvo0hyfVJhuPYVKYpkR6BCQJDOqlhFvo/yaJhhuGWLi2qlPgK70JzIbfktx06r9Sj+Sl63oYvtMhRFGcBiDhT9f4F9x/Kk4DNPuOvfxThASAOK3aZxmMH04CamPgfH0beKfd4zVtHonHuP9brQhvcXNRu/u2QbvGaYFiIgJPCH0mNCtSaklPI+05qZxitO7a4SsLZyzG3APzpPlSnre0zufrPzGcaoUAhGzeBdWUrRUrDudKKVL+Rr20AnNXpLE0mrQ/6/e2gaUwWmHx+zWhAiisL/gtQgxxU9naDwW45JUFgd1ZVTC8fiXe/Dkabgc=
  app: vast-sands-40931
  on:
    repo: RichardPoulson/aspnet-api-heroku
  skip_cleanup: 'true'
